version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"  # Exposing backend on port 3000
    volumes:
      - .:/app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"  # Exposing frontend on port 5173
    volumes:
      - .:/app
    networks:
      - app-network
    environment:
      VITE_API_URL: http://backend:3000  # Connect frontend to backend API

networks:
  app-network:
    driver: bridge
