# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json (or yarn.lock) files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the project (if necessary)
RUN npm run build

# Expose the port your app runs on
EXPOSE 5173

# Command to run the main project
CMD ["npm", "run", "start"]
