version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "4000:3000" # Change the port if necessary
    environment:
      NODE_ENV: production
